plugins {
    id 'com.android.application'
}

android {
    namespace 'com.imscripts.pioneerremote'
    compileSdk 35

    defaultConfig {
        applicationId 'com.imscripts.pioneerremote'
        minSdk 24
        targetSdk 35
        versionCode 6
        versionName '3.0-cloud-sem-bat'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}

dependencies {
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
}
